# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title:            "itfen's blog"
description:      "This is a personal blog of Mingdong on Github Pages."
url:              http://itfen.github.io/md
enforce_ssl:      itfen.github.io

repo:             http://itfen.github.io/md
disqus_name:      "md"
disqus_site_name: "Mingdong's Blog"
cnd:              //mdluo.b0.upaiyun.com/blog

# Author settings
author:
  name:       "Mingdong Luo"
  first_name: "Mingdong"
  email:      mdluo@nsmss.com
  url:        https://mdluo.github.io
  github:     https://github.com/mdluo
  zhihu:      https://www.zhihu.com/people/mdluo
  douban:     https://book.douban.com/people/mdluo/
  v2ex:       https://www.v2ex.com/member/mdluo
  weibo:      http://weibo.com/mindom
  sf:         https://segmentfault.com/u/mdluo

# Build settings
permalink:    /blog/:title/
markdown:     kramdown
highlighter:  rouge

sass:
  style: compressed

paginate:       10
paginate_path:  /blog/page/:num/

gems:     ["jekyll-paginate"]

exclude:  ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
